```{r data generation, echo = FALSE, results = "hide"}
library(exams)
library(gtools)
library(glue)
options(scipen=999)
typ <- match_exams_device()
#--------------------------------------------------------

boteyaz <- sample(4:7,1)
boteyaz
             
botedif <- sample(c(boteyaz-1,boteyaz-2),1)
botedif
plok <- botedif+1
plok

pobmu <- boteyaz-botedif
pobmu
finalt <- pobmu-1
finalt

fakextud <- factorial(boteyaz)
fakextud

fakelegg <- factorial(botedif)
fakelegg

rextafak <- factorial(boteyaz-botedif)
rextafak

rescorr <- fakextud/(rextafak*fakelegg)
rescorr 

incorr1 <- fakextud/rextafak
incorr1

incorr2 <- sample(c(fakelegg/10,fakelegg*2),1)
incorr2

incorr3 <- sample(c(rescorr+10,rescorr-5,fakelegg*3),1)
incorr3

glue_collapse(glue("{boteyaz:1}"), width = boteyaz+1)
faktorialpob <- glue_collapse(boteyaz:1,"*", last = "*")
faktorialpob

glue_collapse(glue("{pobmu:1}"), width = pobmu+1)
faktorialmu <- glue_collapse(pobmu:1,"*", last = "*")
faktorialmu

glue_collapse(glue("{boteyaz:pobmu}"), width = boteyaz+1)
fakpobsimp <- glue_collapse(boteyaz:pobmu,"*", last = "*")
fakpobsimp

glue_collapse(glue("{boteyaz:plok}"), width = boteyaz+1)
finalt<- glue_collapse(boteyaz:plok,"*", last = "*")
finalt

glue_collapse(glue("{botedif:1}"), width = botedif+1)
kip<- glue_collapse(botedif:1,"*", last = "*")
kip

image01csr02 <- '
  \\begin{center}
  \\pgfplotsset{compat=1.18}
	\\begin{tikzpicture}
\\tikzstyle{level 1} = [sibling distance=7.5cm, level distance=1.5cm]
\\tikzstyle{level 2} = [sibling distance=2cm, level distance=1cm]
\\tikzstyle{level 3} = [sibling distance=3.5cm, level distance=1cm]
\\tikzstyle{level 4} = [sibling distance=2.5cm, level distance=1cm]
\\tikzstyle{level 5} = [sibling distance=2cm, level distance=1cm]
\\tikzstyle{level 6} = [sibling distance=1.5cm, level distance=1cm]
\\tikzstyle{arestas}=[rectangle,rounded corners=4pt,fill=orange!30,draw=black,font=\\large]
\\tikzstyle{berdex}=[rectangle,rounded corners=3pt,fill=green!30,draw=black,font=\\large]
\\node[berdex]{¿Están todos los elementos?}
child{
node{SÍ}
    child{
    node{Permutación}
        child{
        node[berdex]{¿Hay repetición?}
            child{
            node{SÍ}
                child{
				        node[arestas]{1}
				        }
            }
            child{
            node{NO}
                child{
				        node[arestas]{2}
                }
				        child{
				        node[berdex]{¿Circular?}
				            child{
				            node[arestas]{3}
				            }
                }   
            }
        }
    }
}
child{
node{NO}
    child{
    node[berdex]{¿Importa el orden?}
        child{
        node{SÍ}
            child{
            node{Variación}
                child{
                node[berdex]{¿Repetición?}
                    child{
                    node{SÍ}
                        child{
				                node[arestas]{4}
				                }
                    }
                    child{
                    node{NO}
                        child{
				                node[arestas]{5}
				                }
                    }
                }
            }
        }
        child{
        node{NO}
            child{
            node{Combinación}
                child{
                node[berdex]{¿Repetición?}
                    child{
                    node{SÍ}
                        child{
				                node[arestas]{6}
				                }
                    }
                    child{
                    node{NO}
                        child{
				                node[arestas]{7}
				                }
                    }
                }
            }
        }
    }    
};
\\end{tikzpicture}   
\\end{center}
'

image02csr02 <- '
  \\centering
	\\begin{tikzpicture}
	\\node{
    \\centering
    \\begin{tabular}{|c|c|c|}
    \\hline
        Opción & Descripción & Fórmula \\\\ \\hline
        1 & Permutación con repetición & $\\mathrm{P}_{a;b;c;...}^{n}=\\frac{n!}{a!\\cdot b!\\cdot c!\\cdot ...}$ \\\\ \\hline
        2 & Permutación sin repetición & $\\mathrm{P}_{n}=n!$ \\\\ \\hline
        3 & Permutación circular & $\\mathrm{PC}_{n}^{}=(n-1)!$ \\\\ \\hline
        4 & Variación con repetición & $\\mathrm{VR}_{k}^{n}=n^{k}$ \\\\ \\hline
        5 & Variación sin repetición & $\\mathrm{V}_{k}^{n}=\\frac{n!}{(n-k)!}$ \\\\ \\hline
        6 & Combinación con repetición & $\\mathrm{CR}_{k}^{n}=\\frac{(k+n-1)!}{(k-1)! \\cdot n!}$ \\\\ \\hline
        7 & Combinación sin repetición & $\\mathrm{C}_{k}^{n}=\\frac{n!}{(n - k)!\\cdot k!}$ \\\\ \\hline
    \\end{tabular}
	};
\\end{tikzpicture} 
'

image03csr02 <- '
\\begin{center}
\\begin{tikzpicture}
\\node {
  $\\begin{aligned}

{V}_{k}^{n}&=\\frac{n!}{(n-k)!* k!} \\\\
{V}_{%s}^{%s}&=\\frac{%s!}{(%s-%s)!* %s! } \\\\
&=\\frac{%s!}{%s!* %s!} \\\\
&=\\frac{%s* %s!}{%s* %s!} \\\\
&=\\frac{%s* \\color{red} \\cancelto{1}{%s!}}{%s* \\color{red} \\cancelto{1}{%s!}} \\\\
{V}_{%s}^{%s}&=%s

  \\end{aligned}$
  };
\\end{tikzpicture}
\\end{center}
'
image03csr02 <- sprintf(image03csr02, botedif, boteyaz, boteyaz, boteyaz, botedif,
                        botedif, boteyaz, pobmu, botedif, finalt, botedif, 
                        faktorialmu, botedif, finalt, botedif, faktorialmu,
                        botedif, botedif, boteyaz, rescorr)
```
Question
========
\
En una bodega hay `r boteyaz` tipos de botellas. ¿De cuántas formas se pueden elegir `r botedif` botellas diferentes?

Answerlist
----------

*  de `r rescorr` formas
*  de `r incorr1` formas
*  de `r incorr2` formas
*  de `r incorr3` formas

Solution
========

\
Para llegar a la respuesta correcta debemos hacernos una serie de preguntas, siguiendo la ruta que nos indica el siguiente diagrama de árbol:

\
```{r image01csr02, warning=FALSE,echo = FALSE, results = "asis"}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
include_tikz(image01csr02, name = "image01csr02", markup = "markdown",
             format = typ,library=c("arrows","perspective","datavisualization",                                    "calc","3d"),packages=c("tikz","booktabs","pgfplots",                                                                "tkz-euclide"), width = "11.5cm")
```
\

* ¿Están todos los elementos? No. La población (`r boteyaz`) no es igual a la muestra (`r botedif`).
* ¿Importa el orden? No. No hay un beneficio por ocupar un lugar específico.
* ¿Hay repetición? No. En la pregunta se solicitan botellas diferentes.
* Entonces, estamos ante un caso de Combinación Sin Repetición (Opción 7):


```{r image02csr02, warning=FALSE,echo = FALSE, results = "asis"}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
include_tikz(image02csr02, name = "image02csr02", markup = "markdown",format = typ, library = c("3d", "babel", "positioning"), packages=c("tikz","xcolor"),width = "11.5cm")
```


Sabiendo que $n=`r boteyaz`$ (población) y que $k=`r botedif`$ (muestra), reemplazamos en la fórmula:

\
```{r image03csr02, warning=FALSE,echo = FALSE, results = "asis"}
if(boteyaz<=5){
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
include_tikz(image03csr02, name = "image03csr02", markup = "markdown",
             format = typ,library=c("arrows","perspective","datavisualization",
                                    "calc","3d"),packages=c("tikz","booktabs",
                                                            "pgfplots", "color",
                                                            "cancel","amsmath",
                                                            "tkz-euclide"), 
             width = "5.5cm")}else{
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
include_tikz(image03csr02, name = "image03csr02", markup = "markdown",
             format = typ,library=c("arrows","perspective","datavisualization",
                                    "calc","3d"),packages=c("tikz","booktabs",
                                                            "pgfplots", "color",
                                                            "cancel","amsmath",
                                                            "tkz-euclide"), 
             width = "4.5cm")
             }
```

<!-- $$ -->
<!-- \require{cancel} -->
<!-- \require{color} -->
<!-- \begin{align*} -->
<!-- \mathrm{V}_{k}^{n}&=\frac{n!}{(n-k)!\cdot k!} \\ -->
<!-- \mathrm{V}_{`r botedif`}^{`r boteyaz`}&=\frac{`r boteyaz`!}{(`r boteyaz`-`r botedif`)!\cdot `r botedif`! } \\ -->
<!-- \mathrm{}&=\frac{`r boteyaz`!}{`r pobmu`!\cdot `r botedif`!} \\ -->
<!-- \mathrm{}&=\frac{`r finalt`\cdot  `r botedif`!}{`r faktorialmu`\cdot  `r botedif`!} \\ -->
<!-- \mathrm{}&=\frac{`r finalt`\cdot \color{Red} \cancelto{1}{`r botedif`!}}{`r faktorialmu`\cdot \color{Red} \cancelto{1}{`r botedif`!}} \\ -->
<!-- \mathrm{V}_{`r botedif`}^{`r boteyaz`}&=`r rescorr` -->
<!-- \end{align*} -->
<!-- $$ -->

Por tanto, con los `r boteyaz` tipos de botellas se pueden elegir `r rescorr` grupos de `r botedif` botellas diferentes.

Answerlist
----------
* Verdadero
* Falso
* Falso
* Falso

Meta-information
================
exname:RadicalPrimo(single-choice)
extype:schoice
exsolution: 1000
exshuffle: TRUE