```{r data generation, echo = FALSE, results = "hide"}
library(exams)
typ <- match_exams_device()

xsubio<-c(sample(5:35,5))
xsubi<-sort(xsubio)
xsubi
frecuencias<-sample(0:30 ,5)

tabla<-data.frame(xsubi,frecuencias)
colnames(tabla)<-c(" Edades" ,"Personas")

total<-(frecuencias[1]+frecuencias[2]+frecuencias[3]+frecuencias[4]+frecuencias[5])

facum1<-frecuencias[1]
facum2<-facum1+frecuencias[2]
facum3<-facum2+frecuencias[3]
facum4<-facum3+frecuencias[4]
facum5<-facum4+frecuencias[5]

xif1<-rep(xsubi[1],frecuencias[1])
xif1
xif2<-rep(xsubi[2],frecuencias[2])
xif3<-rep(xsubi[3],frecuencias[3])
xif4<-rep(xsubi[4],frecuencias[4])
xif5<-rep(xsubi[5],frecuencias[5])
cmna<-c(xif1,xif2,xif3,xif4,xif5)
mna<-median(cmna)
prome<-round(mean(cmna),1)
csmoda<-max(frecuencias[])
if(csmoda==frecuencias[1]){
  moda<-xsubi[1]
}else if(csmoda==frecuencias[2]){
  moda<-xsubi[2]
}else if(csmoda==frecuencias[3]){
  moda<-xsubi[3]
}else if(csmoda==frecuencias[4]){
  moda<-xsubi[4]
}else
  moda<-xsubi[5]

prome2<-sample(c(prome+2,prome-2),1)
mna2<-sample(c(mna+2,mna-2),1)
moda2<-sample(c(moda+2,moda-2,moda),1)

prome3<-sample(c(prome+3,prome-3),1)
mna3<-sample(c(mna+3,mna-3),1)
moda3<-prome+prome

prome4<-sample(c(mna+2,mna-2),1)
mna4<-sample(c(prome+2,prome-2),1)
moda4<-sample(c(mna+3,mna-3),1)

questions<-solutions<-explanations<-NULL
questions[1]<-paste("La media de los datos es ",prome, "; la mediana es " ,mna, "y la moda es " ,moda," .")
solutions[1]<-TRUE
explanations[1]<-"."

questions[2]<-paste("La media de los datos es ",prome2, "; la mediana es " ,mna2, "y la moda es " ,moda2," .")
solutions[2]<-FALSE
explanations[1]<-"."

questions[3]<-paste("La media de los datos es ",prome3, "; la mediana es " ,mna3, "y la moda es " ,moda3," .")
solutions[3]<-FALSE
explanations[1]<-"."

questions[4]<-paste("La media de los datos es ",prome, "; la mediana es " ,mna4, "y la moda es " ,moda," .")

solutions[4]<-FALSE
explanations[1]<-"."
orden<-sample(1:4)
questions<-questions[orden]
solutions<-solutions[orden]
explanations<-explanations[orden]

image08_01 <- '
\\begin{tikzpicture}
  \\node{
    \\begin{tabular}{|c|c|c|}
      \\hline
      Mes & Gasto Mensual & Ingreso Mensual\\\\
          &    (Pesos)    &     (Pesos)\\\\ \\hline
      {Enero}      & {9s}      & {10s}\\\\ \\hline
      {Febrero}      & {12s}      & {13s}\\\\ \\hline
      {Marzo}      & {15s}      & {16s}\\\\ \\hline
      {Abril}      & {18s}      & {19s}\\\\ \\hline
      {Mayo}      & {21s}      & {22s}\\\\ \\hline
      {Junio}      & {24s}      & {25s}\\\\ \\hline
    \\end{tabular}
  };
\\end{tikzpicture}
'
##image08_01 <-sprintf(image08_01, xsubi[1], frecuencias[1], xsubi[2], frecuencias[2], xsubi[3], frecuencias[3], xsubi[4], frecuencias[4], xsubi[5], frecuencias[5])
```

Question
========
La tabla muestra el ingreso y gasto mensual de una familia durante los primeros seis meses del año:
\

```{r image01, warning=FALSE,echo = FALSE, results = "asis"}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
include_tikz(image08_01, name = "grafiko08", markup = "markdown",format = typ, library = c("3d", "babel"), packages=c("tikz","xcolor"),width = "6.5cm")
```

Según esa información,

```{r questionlist, echo = FALSE, results = "asis"}
library(exams)
answerlist(questions, markup = "markdown")
```

Solution
========
```{r solutionlist, echo = FALSE, results = "asis"}
library(exams)
answerlist(ifelse(solutions, "True", "False"), markup = "markdown")
```

Meta-information
================
exname: SaberMat2021_1_08(single-choice)
extype: schoice
exsolution: `r mchoice2string(solutions)`