```{r data generation, echo = FALSE, results = "hide"}
library(exams)

# Cargar la librería y determinar el tipo de dispositivo
typ <- match_exams_device()

# Generar variables aleatorias
ahorrador <- sample(c("José Álvaro","Aquilino","Alexander","Luis Fernando","Juan Manuel","Santiago","Emiliano"),1)
dias_semana <- c("Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado")
num_dias <- 1:7 
numfin <- sample(2:7, 1)
numini <- sample(1:numfin-1, 1)
diafin2 <- dias_semana[numfin]
diaini2 <- dias_semana[numini]
monedas <- sample(c(64,128,256,512,1024,2048,4096), 1)
diasdif <- numfin - numini
ahorroini <- monedas / (2^diasdif)
```

Question
========
Por cada moneda que `r ahorrador` introduce en su alcancía en un día, al siguiente introduce el doble. El `r diafin2`, `r ahorrador` insertó `r monedas` monedas. ¿Cuántas monedas introdujo en su alcancía el `r diaini2` de esa misma semana?


```{r questionlist, echo = FALSE, results = "asis"}
questions <- c(paste(ahorroini))
solutions <- c(TRUE)
explanations <- c(".")
for (i in 1:3) {
  ahorroini2 <- sample(c(monedas/(2^(diasdif+1)), monedas/(3^(diasdif-1))), 1)
  if (ahorroini2 != ahorroini) {
    questions <- c(questions, paste(ahorroini2))
    solutions <- c(solutions, FALSE)
    explanations <- c(explanations, ".")
  } else {
    i <- i-1
  }
}
```

Solution
========
```{r solutionlist, echo = FALSE, results = "asis"}
orden <- sample(1:4)
questions <- questions[orden]
solutions <- solutions[orden]
explanations <- explanations[orden]
```

Meta-information
================
exname: MonedasAhorro2(single-choice)
extype: schoice
exsolution: `r mchoice2string(solutions)`
