```{r data generation, echo = FALSE, results = "hide"}
library(exams)

nprom<-sample(5:10,1)
nprom
prom<-sample(seq(from = 55.0, to = 85.0, by = 1), replace=TRUE,nprom)
prom
  
nprom2<-sample(4:8,1)
nprom2
prom2<-sample(seq(from = 40.0, to = 80.0, by = 1), replace=TRUE,nprom2)
prom2

medianna<-round(median(prom),1)
medianna

medianna2<-round(median(prom2),1)
medianna2

resta<-medianna-medianna2

errprom2<-round(sample(c(resta-2,resta+2),1),digits=1)
errprom2
errprom3<-round(sample(c(resta-3,resta+3),1),digits=1)
errprom3
errprom4<-round(sample(c(resta/2,resta*2),1),digits=1)
errprom4

if(resta!=errprom2 & errprom2!=errprom3 & errprom3!=errprom4){

questions<-solutions<-explanations<-NULL
questions[1]<-paste("",resta," ")
solutions[1]<-TRUE
explanations[1]<-"."

questions[2]<-paste("" ,errprom2,"")
solutions[2]<-FALSE
explanations[2]<-"."

questions[3]<-paste("" ,errprom3,"")
solutions[3]<-FALSE
explanations[3]<-"."

questions[4]<-paste("" ,errprom4,"")
solutions[4]<-FALSE
explanations[4]<-"."

orden<-sample(1:4)
questions<-questions[orden]
solutions<-solutions[orden]
explanations<-explanations[orden]
}
```

Question
========
Si al valor de la mediana de   
\
`r prom`
\

le resto el valor de la mediana de
\

`r prom2`
\

el resultado es
\

```{r questionlist, echo = FALSE, results = "asis"}
library(exams)
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
library(exams)
answerlist(ifelse(solutions, "Verdadero", "Falso"), markup = "markdown")
```

Meta-information
================
exname: Media (single-choice)
extype: schoice
exsolution: `r mchoice2string(solutions)`