```{r data generation, echo = FALSE, results = "hide"}
### Para salidas PDF debe reducirse el tamaño en width = "Xcm"
library(exams)
library(reticulate)
options(tinytex.verbose = TRUE)
typ <- match_exams_device()
use_python('/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/bin/python', required = TRUE)
options(scipen=999)
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
##########################
i <- 1
while(i==1){
chicas <- sample(c(6:20),1)
chicos <- sample(c(6:20),1)
gtr <- chicos*2
salon <- chicos+chicas
kju <- chicas*2
qaw <- sample(c(2,3),1)

ninosf <- chicos*2/3

ninosff <- (chicos*2/3)+1

ninasf <- chicas*3/4
ninasff <- sample(c((chicas*3/4)+1, (chicas*3/4)-1),1)

fute <-ninasf+ninosf
futef <-ninasf+ninosff
futef2 <- ninosf+ninasff

if(fute%%1==0){
 i <- i+1 
}
else i <i
}
##########################
fute
```


Question
========
\
Un estudiante desea calcular la fracción de sus compañeros de salón a los que les gusta jugar fútbol. Para ello, dispone de la siguiente información:\
\
En su salón hay `r chicos` niños y `r chicas` niñas.
\
\
A $\frac{2}{3}$ de los niños de su salón les gusta jugar fútbol.
\
\
A $\frac{3}{4}$ de las niñas de su salón les gusta jugar fútbol.
\
\
Luego, el estudiante realiza el siguiente procedimiento:
\
\
**Paso 1.** Halla la cantidad de compañeros de salón, sumando la cantidad de niños y niñas: `r chicos` + `r chicas` = `r salon`
\
**Paso 2.** Halla la cantidad de niños a los que les gusta jugar fútbol: `r chicos` * $\left( \frac{2}{3} \right)$ = `r ninosf`
\
**Paso 3.** Halla la cantidad de niñas a las que les gusta jugar fútbol: `r chicas` * $\left( \frac{3}{4} \right)$ = `r ninasff`
\
**Paso 4.** Suma la cantidad de niños y niñas a los que les gusta jugar fútbol: `r ninosf` + `r ninasff` = `r futef2`
\
**Paso 5.** Divide el resultado del paso anterior entre la cantidad total de estudiantes: $\frac{`r futef2`}{`r salon`}$
\
\
Al finalizar el procedimiento, el estudiante afirma que la razón de compañeros de salón a los que les gusta jugar fútbol es $\frac{`r futef2`}{`r salon`}$. Sin embargo, su maestra le dice que cometió un error en el procedimiento.
\
\
¿En qué paso cometió el error el estudiante?


Answerlist
----------

- En el paso 4, ya que es incorrecto sumar la cantidad de niños y niñas a los que les gusta jugar fútbol.
<br/> 

- En el paso `r qaw`, ya que `r ninosff` corresponde a la cantidad de niñas a las que les gusta jugar fútbol.
<br/> 

- En el paso 4, ya que la cantidad de niños y niñas a los que les gusta jugar fútbol es `r fute`.
<br/> 

- En el paso 3, ya que la cantidad de niñas a las que les gusta jugar fútbol es `r ninasf`.
<br/> 


Solution
========
\
Al realizar el paso 3, se obtiene $\frac{3}{4}$ * `r chicas` =  $\frac{`r kju`}{4}$  = `r ninasf`. Por tanto, el estudiante cometió el error en el paso 3, ya que la cantidad de niñas a las que les gusta jugar fútbol es `r ninasf`.


Meta-information
================

exname: Triangulos(single-choice)
extype: schoice
exsolution: 0001
exshuffle: TRUE