---
output:
  html_document: default
  pdf_document: default
---
```{r data generation, echo = FALSE, results = "hide"}
### Para salidas PDF debe reducirse el tamaño en width = "Xcm"
library(exams)
library(reticulate)
library(ggplot2)
library(dplyr)

typ <- match_exams_device()
use_python('/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/bin/python', required = TRUE)
options(scipen=999)
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

##########################
clientes <- sample(c(200, 300, 400),1)
##########################
image014587 <- '
\\begin{tikzpicture}
\\pie[text=legend]{10/First, 20/Second, 30/Third, 40/Fourth}
\\end{tikzpicture}
'
image014587 <-sprintf(image014587,p[3],p[6],p[9])
##########################

```


Question
========
\
¿Por qué es tan difícil graficar una pinche torta en Python?
\
<p align="center">
```{python, echo = FALSE, results = "hide", fig.path = "", fig.cap = ""}
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(6, 3), subplot_kw=dict(aspect="equal"))

recipe = ["458 g flour",
          "75 g sugar",
          "250 g butter",
          "300 g berries"]

data = [float(x.split()[0]) for x in recipe]
ingredients = [x.split()[-1] for x in recipe]


def func(pct, allvals):
    absolute = int(np.round(pct/100.*np.sum(allvals)))
    return "{:.1f}%\n({:d} g)".format(pct, absolute)


wedges, texts, autotexts = ax.pie(data, autopct=lambda pct: func(pct, data),
                                  textprops=dict(color="w"))

ax.legend(wedges, ingredients,
          title="Ingredients",
          loc="center left",
          bbox_to_anchor=(1, 0, 0.5, 1))

plt.setp(autotexts, size=8, weight="bold")

ax.set_title("Una torta en Python")

plt.show()
```
</p>


<p align="center">
\centering
```{r image014587, warning=FALSE,echo = FALSE, results = "asis"}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
include_tikz(image014587, name = "image014587", markup = "markdown",format = typ, library = c("3d", "babel","babel", "shadows"), packages=c("tikz","xcolor","pgf-pie","graphicx"),width = "6.5cm")
```
</p>

Answerlist
----------

- Más 
<br/> 

- Menos d
<br/> 

- Menos 
<br/> 

- Más 
<br/> 


Solution
========
\
"No, 

Meta-information
================

exname: Tortas(single-choice)
extype: schoice
exsolution: 1000
exshuffle: TRUE